from dataclasses import dataclass
from enum import Enum
from typing import Any, Dict

class AnalyticsEventType(Enum):
    EXECUTION_UPDATE = "EXECUTION_UPDATE"
    TELEMETRY_UPDATE = "TELEMETRY_UPDATE"
    SCORE_UPDATE = "SCORE_UPDATE"
    LEADERBOARD_UPDATE = "LEADERBOARD_UPDATE"
    SESSION_HEALTH = "SESSION_HEALTH"
    CAMPAIGN_UPDATE = "CAMPAIGN_UPDATE"
    # Tournament Events
    TOURNAMENT_STARTED = "TOURNAMENT_STARTED"
    STAGE_STARTED = "STAGE_STARTED"
    STAGE_COMPLETED = "STAGE_COMPLETED"
    ADVANCEMENT = "ADVANCEMENT"
    ELIMINATION = "ELIMINATION"
    WINNER_DECLARED = "WINNER_DECLARED"
    # Evaluation Events
    EVALUATION_STARTED = "EVALUATION_STARTED"
    EVALUATION_COMPLETED = "EVALUATION_COMPLETED"
    PROFILE_UPDATED = "PROFILE_UPDATED"
    REPORT_GENERATED = "REPORT_GENERATED"
    ADVERSARIAL_TEST_COMPLETED = "ADVERSARIAL_TEST_COMPLETED"
    # Federation Events
    NODE_REGISTERED = "NODE_REGISTERED"
    NODE_REMOVED = "NODE_REMOVED"
    NODE_HEARTBEAT = "NODE_HEARTBEAT"
    JOB_ASSIGNED = "JOB_ASSIGNED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    ARTIFACT_REPLICATED = "ARTIFACT_REPLICATED"
    FEDERATION_SYNC_COMPLETED = "FEDERATION_SYNC_COMPLETED"
    LEADER_ELECTED = "LEADER_ELECTED"
    LEADER_REMOVED = "LEADER_REMOVED"
    QUORUM_LOST = "QUORUM_LOST"
    QUORUM_RESTORED = "QUORUM_RESTORED"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    SNAPSHOT_LOADED = "SNAPSHOT_LOADED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_COMPLETED = "RECOVERY_COMPLETED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_RELEASED = "LOCK_RELEASED"
    MEMBERSHIP_CHANGED = "MEMBERSHIP_CHANGED"
    LOG_COMPACTED = "LOG_COMPACTED"
    UPGRADE_POLICY_UPDATED = "UPGRADE_POLICY_UPDATED"
    SNAPSHOT_CHUNK_RECEIVED = "SNAPSHOT_CHUNK_RECEIVED"
    NODE_HEALTH_DEGRADED = "NODE_HEALTH_DEGRADED"
    NODE_HEALTH_RESTORED = "NODE_HEALTH_RESTORED"
    SELF_HEAL_TRIGGERED = "SELF_HEAL_TRIGGERED"
    SELF_HEAL_COMPLETED = "SELF_HEAL_COMPLETED"
    WORKLOAD_REBALANCED = "WORKLOAD_REBALANCED"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"
    ANOMALY_CLEARED = "ANOMALY_CLEARED"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    POLICY_ACTION_APPLIED = "POLICY_ACTION_APPLIED"
    CAPACITY_FORECAST_GENERATED = "CAPACITY_FORECAST_GENERATED"
    ORCHESTRATION_DECISION = "ORCHESTRATION_DECISION"
    AUTONOMOUS_ACTION_EXECUTED = "AUTONOMOUS_ACTION_EXECUTED"
    RESOURCE_HOTSPOT_DETECTED = "RESOURCE_HOTSPOT_DETECTED"
    RESOURCE_HOTSPOT_RESOLVED = "RESOURCE_HOTSPOT_RESOLVED"

@dataclass
class AnalyticsEvent:
    event_id: str
    timestamp_ns: int
    event_type: AnalyticsEventType
    source: str
    payload: Dict[str, Any]
