# Strategic service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iicpc.fullname" . }}-strategic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iicpc.labels" . | nindent 4 }}
    app: strategic
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: {{ .Values.strategic.service.type }}
  ports:
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
  selector:
    app: strategic