apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: iicpc-platform
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/orbaps/exchange
  ref:
    branch: main
  ignore: |
    !iac/helm/iicpc-platform/
