from __future__ import annotations

from dataclasses import dataclass

# ---
# Performance aggregates and composite scores generated by telemetry/validation diffs
# ---

@dataclass
class WeightConfig:
    """Weights representing relative importance of each metric category in final score."""
    w_correctness: float
    w_latency: float
    w_throughput: float
    w_stability: float
    w_resilience: float


@dataclass
class TelemetryAggregates:
    """Consolidated performance telemetry from clickhouse streams for a run."""
    p50_latency_ns: int
    p90_latency_ns: int
    p99_latency_ns: int
    p999_latency_ns: int
    sustained_tps: float
    peak_tps: float
    latency_stddev: float
    latency_mean: float
    error_rate: float
    chaos_events_handled: int
    chaos_events_total: int


@dataclass
class CompositeScore:
    """Overall run score components and gating status."""
    run_id: str
    submission_id: str
    total_score: float
    correctness_score: float
    latency_score: float
    throughput_score: float
    stability_score: float
    resilience_score: float
    gated: bool
