from __future__ import annotations

import dataclasses
from enum import Enum, IntEnum
from typing import List

# --- Domain Enumerations & Structures ---

class Side(IntEnum):
    """Represents the side of an order (Buy/Sell)."""
    SIDE_UNSPECIFIED = 0
    BUY = 1
    SELL = 2


class OrderType(IntEnum):
    """Represents the type of an order (Limit, Market, Stop-Limit)."""
    ORDER_TYPE_UNSPECIFIED = 0
    LIMIT = 1
    MARKET = 2
    STOP_LIMIT = 3


class TimeInForce(IntEnum):
    """Represents the Time in Force instructions for an order."""
    TIF_UNSPECIFIED = 0
    GFD = 1
    GTC = 2
    IOC = 3
    FOK = 4


class ExecType(IntEnum):
    """Represents the execution report transaction types."""
    EXEC_TYPE_UNSPECIFIED = 0
    NEW = 1
    REJECTED = 2
    PARTIALLY_FILLED = 3
    FILLED = 4
    CANCELED = 5
    EXPIRED = 6
    REPLACED = 7
    SMP_CANCELED = 8


class RejectReason(IntEnum):
    """Represents the reason why an order was rejected by the engine."""
    REJECT_REASON_UNSPECIFIED = 0
    INVALID_PRICE = 1
    INVALID_QUANTITY = 2
    INVALID_SYMBOL = 3
    INVALID_SIDE = 4
    INVALID_ORDER_TYPE = 5
    DUPLICATE_CLIENT_ORDER_ID = 6
    SESSION_NOT_ACCEPTING = 7
    FOK_WOULD_NOT_FILL = 8
    UNKNOWN_ORDER_ID = 9
    ORDER_ALREADY_TERMINAL = 10
    SMP_REJECT = 11


class OrderState(Enum):
    """Represents the internal state of an order in the matching engine."""
    PENDING_NEW = "PENDING_NEW"
    NEW = "NEW"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    EXPIRED = "EXPIRED"
    REPLACED = "REPLACED"
    REJECTED = "REJECTED"
    SMP_CANCELED = "SMP_CANCELED"


class SessionState(IntEnum):
    """Represents the exchange session states."""
    SESSION_STATE_UNSPECIFIED = 0
    CLOSED = 1
    PRE_OPEN = 2
    NO_CANCEL = 3
    CONTINUOUS = 4
    HALTED = 5
    PRE_CLOSE = 6
    MAINTENANCE = 7


@dataclasses.dataclass(frozen=True)
class PriceLevel:
    """Represents an aggregate level of orders at a specific price."""
    price: int
    quantity: int
    order_count: int


@dataclasses.dataclass(frozen=True)
class BookSnapshot:
    """A point-in-time snapshot of the order book for a given symbol."""
    sequence_no: int
    timestamp_ns: int
    symbol: str
    bids: List[PriceLevel]
    asks: List[PriceLevel]


@dataclasses.dataclass(frozen=True)
class ExecutionReport:
    """Outbound execution report generated by the matching engine."""
    sequence_no: int
    timestamp_ns: int
    execution_id: int
    order_id: int
    client_order_id: str
    symbol: str
    side: Side
    exec_type: ExecType
    last_price: int
    last_qty: int
    leaves_qty: int
    cumulative_qty: int
    original_qty: int
    reject_reason: RejectReason
    match_order_id: int


@dataclasses.dataclass(frozen=True)
class FieldDiff:
    """Represents a difference in a single field of an execution report."""
    field: str
    expected: str
    actual: str


@dataclasses.dataclass(frozen=True)
class LevelDiff:
    """Represents a difference in a book depth level."""
    side: str
    price: int
    expected_qty: int
    actual_qty: int
    expected_count: int
    actual_count: int
